"use client"

import * as React from "react"
import Link from "next/link"
import { ChevronDown } from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

const tools = [
  {
    category: "PDF Tools",
    tools: [
      {
        name: "Merge PDF",
        description: "Combine multiple PDFs into one file",
        href: "/tools/pdf-merge",
      },
      {
        name: "Split PDF",
        description: "Extract specific pages from a PDF",
        href: "/tools/pdf-split",
      },
      {
        name: "Compress PDF",
        description: "Reduce PDF file size while maintaining quality",
        href: "/tools/pdf-compress",
      },
      {
        name: "PDF to Images",
        description: "Convert PDF pages to JPG, PNG, or other formats",
        href: "/tools/pdf-to-images",
      },
      {
        name: "Images to PDF",
        description: "Combine multiple images into a single PDF",
        href: "/tools/images-to-pdf",
      },
      {
        name: "Add Watermark",
        description: "Add text or image watermarks to PDFs",
        href: "/tools/pdf-watermark",
      },
      {
        name: "Add Page Numbers",
        description: "Add page numbers to your PDF documents",
        href: "/tools/pdf-page-numbers",
      },
      {
        name: "OCR PDF",
        description: "Make scanned PDFs searchable with OCR",
        href: "/tools/pdf-ocr",
      },
    ],
  },
  {
    category: "Text Tools",
    tools: [
      {
        name: "Word Counter",
        description: "Count words, characters, and paragraphs",
        href: "/tools/word-counter",
      },
      {
        name: "Case Converter",
        description: "Convert text to uppercase, lowercase, or title case",
        href: "/tools/case-converter",
      },
      {
        name: "AI Text Detector",
        description: "Check if text was generated by AI",
        href: "/tools/ai-detector",
      },
      {
        name: "Text Summarizer",
        description: "Summarize long text into key points",
        href: "/tools/text-summarizer",
      },
    ],
  },
]

export function ToolsMegaMenu() {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="flex items-center space-x-1">
          <span>Tools</span>
          <ChevronDown className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent 
        className="w-[600px] p-4" 
        align="start"
        sideOffset={8}
      >
        <div className="grid grid-cols-2 gap-6">
          {tools.map((category) => (
            <div key={category.category} className="space-y-3">
              <h3 className="font-semibold text-sm text-foreground">
                {category.category}
              </h3>
              <div className="space-y-2">
                {category.tools.map((tool) => (
                  <Link
                    key={tool.href}
                    href={tool.href}
                    className="block p-2 rounded-md hover:bg-accent transition-colors group"
                  >
                    <div className="font-medium text-sm group-hover:text-accent-foreground">
                      {tool.name}
                    </div>
                    <div className="text-xs text-muted-foreground group-hover:text-accent-foreground/80">
                      {tool.description}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          ))}
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
