name = "webspind-api"
main = "worker.js"
compatibility_date = "2024-01-15"

# Environment variables (set these in Cloudflare Workers dashboard)
[vars]
ENVIRONMENT = "production"

# KV namespaces for data storage
[[kv_namespaces]]
binding = "USAGE_STORE"
id = "your-usage-store-kv-id"
preview_id = "your-usage-store-preview-kv-id"

[[kv_namespaces]]
binding = "LICENSE_STORE"
id = "your-license-store-kv-id"
preview_id = "your-license-store-preview-kv-id"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "your-session-store-kv-id"
preview_id = "your-session-store-preview-kv-id"

# Custom domain (optional)
# [env.production]
# route = "api.webspind.com/*"

# Secrets (set these via wrangler secret put)
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put STRIPE_WEBHOOK_SECRET
